export const GAME_TYPE_INPUTS_old = ['Slots', 'Live dealer', 'Slingo', 'Bingo', 'Casino', 'Poker', 'Instant Win'];
export const GAME_TYPE_INPUTS = [
    'Live Dealer',
    'Slingo',
    'Bingo',
    'Casino',
    'Live Casino',
    'Poker',
    'Scratchcards',
    'Slots',
    'Soft',
    'Video Poker',
    'Sports',
    'Instant Win',
    'Keno',
    'Table',
    'Live Baccarat',
    'Live Bingo',
    'Live Blackjack',
    'Live Dice',
    'Live Game Show',
    'Live Poker',
    'Live Roulette',
    'Live Slot',
    "Baccarat",
    "Blackjack",
    "Card Game",
    "Dice",
    "Game Show",
    "Roulette",
    "Solitaire",
    "Wheel"
];

export const SUB_GAME_TYPE_INPUTS = [
    'Live dealer',
    'Slingo',
    'Bingo',
    'Casino',
    'Live Casino',
    'Poker',
    'Scratchcards',
    'Slots',
    'Soft',
    'Video Poker',
    'Sports',
    'Instant Win',
    'Keno',
    'Table',
    'Auto Roulette',
    'Baccarat Variant',
    'BetOn Variant',
    'Bingo Game Show',
    'Limited Blackjack',
    'Live Talking Head Show',
    'Multiplier Baccarat',
    'Multiplier Dice',
    'Multiplier Roulette',
    'Multiplier Unlimited Blackjack',
    'Other Game Show',
    'Poker Variant',
    'Speed Roulette',
    'Standard Baccarat',
    'Standard Dice',
    'Standard Live Slot',
    'Standard Roulette',
    'Unlimited Blackjack',
    'Wheel Game show',
    "Dual Play Roulette",
];

export const FEDERAL_GAME_TYPE_INPUTS = [
    'Bingo',
    'Casino',
    'Poker',
    'Scratchcards',
    'Slots',
    'Soft',
    'Video Poker',
    'Sports',
    'Instant Win',
    'Keno',
    'Table',
];

export const CONTRACT_GAME_TYPE_INPUTS = [
    'Branded',
    'Standard',
    'Premium',
    'SSU',
    'Table/Scratchcard'
];

export const TAX_PRODUCT_TYPE_INPUTS = [
    'Table',
    'Slots',
    'Casino'
];

export const GAME_AGGREGATOR_INPUTS = [
    '1X2 Network',
    '3Radical',
    '4ThePlayer',
    'AGS',
    'Ainsworth',
    'Air Dice',
    'Amaya',
    'Amusnet',
    'Anaxi',
    'Arcadia',
    'Aristocrat',
    'Asia Gaming',
    'Aspect Gaming',
    'Authentic Gaming',
    'AvatarUX',
    'BF Games',
    'BetGames',
    'BetWorks',
    'Betsoft',
    'Big Time Gaming',
    'Bingo',
    'Blueprint',
    'Bombay Club',
    'Booming Games',
    'Booongo',
    'Bragg',
    'Colossus',
    'Concept Gaming',
    'DFG',
    'DGC',
    'DWG',
    'Design Works Gaming',
    'ELK Studios',
    'Eyecon',
    'Electric Elephant',
    'Engage RGS',
    'Espresso Games',
    'Everi',
    'Evolution Gaming',
    'Evoplay',
    'Ezugi',
    'FSB Tech',
    'Fantasma Games',
    'GAN',
    'GGLUS',
    'Gaming Realms',
    'GameArt',
    'GameCode',
    'GameTech IOM',
    'Gameplay Interactive',
    'Games Global',
    'Gamesys',
    'Gamesys Games',
    'Gaming Corps',
    'Gaming Realms',
    'Gamomat',
    'Gamevy',
    'Genesis Gaming',
    'Greentube',
    'Hub88',
    'HungryBear',
    'IGT',
    'Incredible Technologies',
    'Inspired',
    'Jelly',
    'Kalamba Games',
    'Kiron Interactive',
    'Konami',
    'Leander Games',
    'Light & Wonder',
    'Lightning Box',
    'Lotus Live Gaming',
    'MPlay',
    'Manna Play',
    'Metric Gaming',
    'MicroGaming',
    'Mikado',
    'MultiSlot',
    'N2Live',
    'NYX',
    'NetEnt',
    'NoLimit City',
    'Novomatic',
    'ODDSworks',
    'OMI Gaming',
    'OnAir Entertainment',
    'OneTouch',
    'Octoplay',
    'Octopus Gaming',
    'Oryx Gaming',
    'Pariplay',
    'ParlayBay',
    'Play N Go',
    'Playgon',
    'Playson',
    'Playtech',
    'Playzido',
    'Pocket Games',
    'Poker',
    'PragmaticPlay',
    'Print Studios',
    'Push Gaming',
    'Quickfire',
    'Quickspin',
    'RAW',
    'RTG Asia',
    'RareStone',
    'Realistic Games',
    'Red Rake',
    'Red Tiger',
    'ReelPlay',
    'Reloaded Gaming',
    'Relax',
    'ReSpin',
    'Revolver Gaming',
    'Rogue',
    'Roxor Gaming',
    'SAGaming',
    'SDK',
    'SG Digital',
    'SGaming',
    'Sands',
    'Sapphire Gaming',
    'SimplePlay',
    'Skywind',
    'Slingo Originals',
    'Slot Factory',
    'Slotmill',
    'SmartSoft',
    'Spin',
    'Spinomenal',
    'SportCaller',
    'Spribe',
    'Stakelogic',
    'Stakelogic V2 - STL',
    'Super Spade',
    'Thunderkick',
    'Tom Horn Gaming',
    'TopSpin',
    'Triple PG',
    'Vision RGS',
    'Vivo Gaming',
    'WMS',
    'Wazdan',
    'WhiteHatStudios',
    'Wizard Games',
    'Woohoo',
    'Xpress Gaming',
    'YGG Drasil'
]

export const GAME_PROVIDER_INPUTS = [
    '1X2 Network',
    '3Radical',
    '4ThePlayer',
    'AGS',
    'Ainsworth',
    'Air Dice',
    'Amaya',
    'Amusnet',
    'Anaxi',
    'Arcadia',
    'Aristocrat',
    'Asia Gaming',
    'Aspect Gaming',
    'Authentic Gaming',
    'AvatarUX',
    'BF Games',
    'BetGames',
    'BetWorks',
    'Betsoft',
    'Big Time Gaming',
    'Bingo',
    'Blueprint',
    'Bombay Club',
    'Booming Games',
    'Booongo',
    'Bragg',
    'Colossus',
    'Concept Gaming',
    'DFG',
    'DGC',
    'DWG',
    'Design Works Gaming',
    'ELK Studios',
    'Eyecon',
    'Electric Elephant',
    'Engage RGS',
    'Espresso Games',
    'Everi',
    'Evolution Gaming',
    'Evoplay',
    'Ezugi',
    'FSB Tech',
    'Fantasma Games',
    'GAN',
    'GGLUS',
    'Gaming Realms',
    'GameArt',
    'GameCode',
    'GameTech IOM',
    'Gameplay Interactive',
    'Games Global',
    'Gamesys',
    'Gamesys Games',
    'Gaming Corps',
    'Gaming Realms',
    'Gamomat',
    'Gamevy',
    'Genesis Gaming',
    'Greentube',
    'Hub88',
    'HungryBear',
    'IGT',
    'Incredible Technologies',
    'Inspired',
    'Jelly',
    'Kalamba Games',
    'Kiron Interactive',
    'Konami',
    'Leander Games',
    'Light & Wonder',
    'Lightning Box',
    'Lotus Live Gaming',
    'MPlay',
    'Manna Play',
    'Metric Gaming',
    'MicroGaming',
    'Mikado',
    'MultiSlot',
    'N2Live',
    'NYX',
    'NetEnt',
    'NoLimit City',
    'Novomatic',
    'ODDSworks',
    'OMI Gaming',
    'OnAir Entertainment',
    'OneTouch',
    'Octoplay',
    'Octopus Gaming',
    'Oryx Gaming',
    'Pariplay',
    'ParlayBay',
    'Play N Go',
    'Playgon',
    'Playson',
    'Playtech',
    'Playzido',
    'Pocket Games',
    'Poker',
    'PragmaticPlay',
    'Print Studios',
    'Push Gaming',
    'Quickfire',
    'Quickspin',
    'RAW',
    'RTG Asia',
    'RareStone',
    'Realistic Games',
    'Red Rake',
    'Red Tiger',
    'ReelPlay',
    'Reloaded Gaming',
    'Relax',
    'ReSpin',
    'Revolver Gaming',
    'Rogue',
    'Roxor Gaming',
    'SAGaming',
    'SDK',
    'SG Digital',
    'SGaming',
    'Sands',
    'Sapphire Gaming',
    'SimplePlay',
    'Skywind',
    'Slingo Originals',
    'Slot Factory',
    'Slotmill',
    'SmartSoft',
    'Spin',
    'Spinomenal',
    'SportCaller',
    'Spribe',
    'Stakelogic',
    'Stakelogic V2 - STL',
    'Super Spade',
    'Thunderkick',
    'Tom Horn Gaming',
    'TopSpin',
    'Triple PG',
    'Vision RGS',
    'Vivo Gaming',
    'WMS',
    'Wazdan',
    'WhiteHatStudios',
    'Wizard Games',
    'Woohoo',
    'Xpress Gaming',
    'YGG Drasil'
];

export const GAME_STUDIO_INPUTS = [
    '4ThePlayer',
    'Alchemy Gaming',
    'All41 Studios',
    'Area Vegas',
    'Aristocrat',
    'Aurum Signature Studios',
    'Bally',
    'Baltic Studios',
    'Barcrest',
    'Barstruck',
    'Big Time Gaming',
    'Blueprint',
    'Chance Interactive',
    'Coin Machine Gaming',
    'Crazy Tooth Studio',
    'Crucible Gaming',
    'Daily Free Games',
    'Elk Studios',
    'Endemol',
    'Everi',
    'Evolution Gaming',
    'Eyecon',
    'Foxium',
    'Fortune Factory Studios',
    'Gameburger Studios',
    'Games Global',
    'Games Global (GGL)',
    'Gamevy',
    'Gaming Arts',
    'Gold Coin Studios',
    'Golden Hero',
    'Hammertime Games',
    'High Limit Studios',
    'Hungry Bear',
    'IGT',
    'Indigo Magic',
    'Inspired Gaming',
    'Just for the Win',
    'King Show Games',
    'Light & Wonder',
    'Lightning Box',
    'Lucksome Studios',
    'MGA',
    'MicroGaming',
    'Nailed It Games',
    'Neon Valley Studios',
    'NetEnt',
    'Northern Lights',
    'NYX',
    'Oros',
    'Pariplay',
    'Pear Fiction Gaming',
    'Play N Go',
    'Playtech',
    'Playzido',
    'PragmaticPlay',
    'Print Studios',
    'Pulse 8',
    'Raw',
    'Red 7',
    'Red Tiger',
    'Rogue',
    'Roxor Gaming',
    'Scientific Games',
    'Shufflemaster',
    'Side City',
    'Slingo',
    'Slingshot Studios',
    'Snowborn Games',
    'Spin Play Games',
    'Stakelogic',
    'Stormcraft Studios',
    'Switch Studios',
    'Triple Edge Studios',
    'White Hat Studios',
    'Wishbone Games',
    'WMS'
];

export const CASINO_ONLY_INPUTS = ['Game Show', 'Roulette', 'Blackjack', 'Baccarat', 'Poker', 'Other'];

export const SLOTS_ONLY_FIELDS = [
    { id: 'reel', labelText: 'Select Reel' },
    { id: 'winLines', labelText: 'Select Win Lines' },
    { id: 'winLineType', labelText: 'Select Win Line Type' },
    { id: 'waysToWin', labelText: 'Select Ways To Win' },
    { id: 'symbolType', labelText: 'Select Symbol Type' },
    { id: 'symbolCount', labelText: 'Enter Symbol Count' },
    { id: 'maxMultiplier', labelText: 'Max Multiplier' },
    { id: 'isJackpot', labelText: 'Is Jackpot?' },
    { id: 'isJackpotFixedPrize', labelText: 'Is Jackpot Fixed Prize?' },
    { id: 'isJackpotInGameProgressive', labelText: 'Is Jackpot In Game Progessive?' },
    { id: 'isJackpotPlatformProgressive', labelText: 'Is Jackpot Platform Progressive?' },
    { id: 'isPersistence', labelText: 'Is Persistence?' },
];

export const SLOTS_REELS = [
    'Megaways', 'Tap', 'Crash',
    '3-3', '3-5', '4-5', '5-3', '5-4', '5-5',
    '6-3', '6-4', '6-5', '6-6', '6-8',
    '7-6', '7-7', 'Other'
];

export const WIN_LINES = [
    '1', '5', '9', '10', '12', '15', '20',
    '25', '30', '40', '50', '50+', 'Other'
];

export const WIN_LINE_TYPES = [
    'L2R', 'Cluster', 'Cluster pays', 'Megaways', 'Bothways',
    'Scatter pays', 'Ways', 'Crash', 'Plinko', 'Other'
];

export const WAYS_TO_WIN = [
    '243', '432', '720', '1024', '2304', '3072',
    '3125', '4096', '4608', '15625', '46656', '117649',
    '200704', '262144', '99225', 'Other'
];

export const SYMBOL_TYPES = ['Royals', 'Suits', 'BarX', 'Fruits', 'Gems', 'Cash/Bullion', 'Other'];

export const GAME_METADATA_THEMES = [
    'Action',
    'Adventure',
    'Africa',
    'America',
    'Americana',
    'Ancient Civilizations',
    'Animals',
    'Ape',
    'Arabian',
    'Arabic',
    'Asian',
    'Atlantis',
    'BESPOKE',
    'Bank',
    'Birds',
    'Bison/Buffalo',
    'Branded',
    'Bubble',
    'Candy/Sweets',
    'Cats',
    'Chinese',
    'Christmas',
    'Classic',
    'Retro',
    'Crime',
    'Detective',
    'Devil',
    'Dinosaurs',
    'Dragon',
    'Drums',
    'Egypt',
    'Egyptian',
    'Elements',
    'Espionage',
    'Fairy Tale',
    'Fantasy',
    'Farm',
    'Fire',
    'Fishing',
    'Fruit',
    'Gangsters',
    'Gems',
    'Genie',
    'Gods',
    'Gold',
    'Greece',
    'Horror',
    'Irish',
    'Island',
    'Historic',
    'Joker',
    'Jungle',
    'King',
    'Latin American Ancient Civilisations',
    'Licensed',
    'Luxury',
    'Magic',
    'Magic/Alchemy',
    'Masks',
    'Mayan/Aztec',
    'Medieval',
    'Mexico',
    'Mining',
    'Mining/Prospector',
    'Money',
    'Moon',
    'Music',
    'Mythology',
    'Nature',
    'No Theme',
    'Other',
    'Oz',
    'Pets',
    'Pig',
    'Piggy',
    'Pirate',
    'Poultry',
    'Prehistoric',
    'Robbery',
    'Roman',
    'Romance/Love',
    'Rome',
    'Royal',
    'Sevens',
    'Space',
    'Sports',
    'Steampunk',
    'Sweets',
    'Tiki',
    'Tomb Raider',
    'Train',
    'Tropical',
    'Underwater',
    'Urban',
    'Vampires',
    'Casino/Vegas',
    'Vikings',
    'Volcano',
    'Water',
    'Western',
    'Wild West',
    'Winter',
    'Wolf',
    'Xmas'
];

export const GAME_METADATA_FEATURES = [
    '3 reel slot mechanic',
    'Any Adjacent Pays',
    'Bi-directional Pays',
    'Bidirectional pays',
    'Bonus Buy',
    'Bonus Game',
    'Bonus Recharge',
    'Bonus wheel',
    'Book feature',
    'Boost Mode',
    'Boost Feature',
    'Buy Feature',
    'Buy Bonus',
    'Cascading Reels',
    'Cash Collect',
    'Collection Pot',
    'Countdown Clock',
    'Crash',
    'Epic Strike',
    'Expanding Reels',
    'Expanding Symbols',
    'Expanding Wilds',
    'Feature Gamble',
    'Fixed Jackpot',
    'Fortune Bet Feature',
    'Fortune Play',
    'Free Games',
    'Free Rounds',
    'Free Spins',
    'Gamble',
    'Gamble to Cash Prize',
    'Gamble to Feature',
    'Growing Jackpots / Modifiers',
    'Guaranteed Symbols',
    'Guaranteed Wins',
    'Hold and Win',
    'HyperSpins',
    'Increasing / Varying Pay Ways',
    'Increasing/Varying payways',
    'Instant Prize',
    'Jumbo Symbols',
    'Ladder Bonus',
    'Link & Win',
    'Link & Win Extended',
    'Link & Win Modifiers',
    'Match to Win',
    'Megaways',
    'Multi Chase',
    'Multi Feature',
    'Multi-Grid',
    'Multi-grid',
    'Multipliers',
    'Multipliers (With or without wilds)',
    'Multiple Entry Points for Bonus',
    'Mystery Symbols',
    'No Feature',
    'Nudging Symbols',
    'Other Monetisation',
    'Other Wilds',
    'Paid Feature',
    'Pay Anywhere',
    'Pick Feature',
    'Pick Me',
    'Player Choice',
    'Plinko',
    'Power Combo',
    'Pre-Bonus Game for Modifiers',
    'Random Wilds',
    'Random Win Creation',
    'Respin',
    'Returning Symbols',
    'Reveal to win bonus',
    'Rolling Reels',
    'Scatter Symbols',
    'Scatter Wilds/Symbols',
    'Spin Chance',
    'Spreading Wilds',
    'Stacked Symbols',
    'Stacked Wilds',
    'Static Jackpot',
    'Static Jackpots',
    'Sticky Symbols',
    'Sticky Wilds',
    'Super Free Spins',
    'Symbol Upgrade',
    'Synced Reels',
    'Token/Reel Collection',
    'Trail',
    'Trail Feature',
    'Unlockable Modifiers',
    'Upsizer',
    'Walking Symbols',
    'Wheel',
    'Wild Links',
    'Wild Reels',
    'Wild Scrolls',
    'Wilds',
    'XUP'
];

export const GAME_METADATA_BRANDS = ['Yes', 'No', 'Monopoly', 'The Godfather', 'Deal or no deal'];
